### ISSUE TITLE
Firewalld has slow startup on Manjaro 

### ISSUE THREAD

**Issue by ryanvade** [t-woerner/firewalld#56]
I am running firewalld on Manjaro Linux with GNOME 3.18.3.  System startup is really slow because firewalld is taking almost 20 seconds to start.  Is there anything I can do to speed up firewalld?
```
 systemd-analyze blame
         19.929s firewalld.service
          9.189s systemd-journald.service
          4.505s dev-sda3.device
          4.455s systemd-modules-load.service
          4.076s ModemManager.service
          2.821s systemd-fsck@dev-disk-by\x2duuid-fca3eb5c\x2d2981\x2d44c6\x2d8108\x2d9eef32e823a7.service
          2.791s polkit.service
          2.002s plymouth-quit-wait.service
          1.922s avahi-daemon.service
          1.784s systemd-vconsole-setup.service
          1.679s thermald.service
          1.486s systemd-journal-flush.service
          1.149s systemd-logind.service
          1.146s accounts-daemon.service
           955ms systemd-sysctl.service
           953ms gdm-plymouth.service
           867ms systemd-tmpfiles-setup-dev.service
           761ms bluetooth.service
           701ms systemd-user-sessions.service
           655ms systemd-binfmt.service
           608ms sys-kernel-debug.mount
           606ms dev-hugepages.mount
           592ms freefall@-dev-sda.service
           487ms systemd-hostnamed.service
           424ms home.mount
           413ms systemd-udevd.service
           387ms user@120.service
           316ms tmp.mount
           315ms systemd-remount-fs.service
           313ms dev-mqueue.mount
           266ms proc-sys-fs-binfmt_misc.mount
           249ms udisks2.service
           242ms systemd-rfkill.service
           239ms packagekit.service
           200ms colord.service
           169ms NetworkManager.service
           167ms systemd-timedated.service
           164ms systemd-backlight@backlight:intel_backlight.service
           149ms alsa-restore.service
           134ms systemd-localed.service
           131ms upower.service
           128ms systemd-tmpfiles-setup.service
           120ms sys-kernel-config.mount
           107ms systemd-timesyncd.service
            94ms systemd-udev-trigger.service
            88ms systemd-random-seed.service
            74ms wpa_supplicant.service
            64ms user@1000.service
            49ms systemd-update-utmp.service
            29ms rtkit-daemon.service
            26ms plymouth-start.service
            24ms geoclue.service
            20ms kmod-static-nodes.service
            13ms plymouth-read-write.service
             3ms sys-fs-fuse-connections.mount
```
```
 systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2015-11-15 15:35:35 CST; 2min 4s ago
 Main PID: 606 (firewalld)
   CGroup: /system.slice/firewalld.service
           └─606 /usr/bin/python -Es /usr/bin/firewalld --nofork --nopid

Nov 15 15:35:35 ryan-linux-laptop systemd[1]: Started firewalld - dynamic firewall daemon.
Nov 15 15:37:07 ryan-linux-laptop /firewalld[606]: 2015-11-15 15:37:07 ERROR: UNKNOWN_INTERFACE: 'wlp10s0' is not in any zone
```

**Comment by ryanvade** [comment]
![workspace 2_129](https://cloud.githubusercontent.com/assets/1910293/11171184/4946bcf0-8baf-11e5-8a22-7fff4f303a35.png)

**Comment by t-woerner** [comment]
I think there is an issue while booting on your machine. All services in your machine are taking a lot of time to start. Please have a look at the system log to see if there are errors somewhere while booting.

Please attach the output of "systemd-analyze plot" and "systemd-analyze dump" and "du -ks /etc/firewalld /usr/lib/firewalld"

**Comment by ryanvade** [comment]
After disabling both firewalld and ModemManager (For some reason it was enabled)
```
systemd-analyze blame
          5.889s dev-sda3.device
          4.254s bluetooth.service
          3.754s systemd-logind.service
          3.568s alsa-restore.service
          3.544s freefall@-dev-sda.service
          3.487s thermald.service
          3.487s NetworkManager.service
          3.486s avahi-daemon.service
          3.356s systemd-user-sessions.service
          2.250s plymouth-quit-wait.service
          1.866s systemd-rfkill.service
          1.808s systemd-journald.service
          1.540s systemd-vconsole-setup.service
          1.292s accounts-daemon.service
          1.093s systemd-udevd.service
           884ms systemd-hostnamed.service
           726ms dev-hugepages.mount
           655ms sys-kernel-debug.mount
           652ms systemd-fsck@dev-disk-by\x2duuid-fca3eb5c\x2d2981\x2d44c6\x2d81
           575ms systemd-tmpfiles-setup-dev.service
           548ms dev-mqueue.mount
           531ms polkit.service
           509ms tmp.mount
           502ms systemd-sysctl.service
           492ms colord.service
           407ms systemd-binfmt.service
           404ms systemd-remount-fs.service
           394ms home.mount
           363ms systemd-modules-load.service
           361ms kmod-static-nodes.service
           310ms user@120.service
           310ms sys-kernel-config.mount
           265ms systemd-journal-flush.service
           187ms packagekit.service
           186ms systemd-random-seed.service
           169ms systemd-udev-trigger.service
           146ms systemd-timedated.service
           127ms systemd-backlight@backlight:intel_backlight.service
           121ms systemd-localed.service
           116ms proc-sys-fs-binfmt_misc.mount
           105ms udisks2.service
            94ms systemd-timesyncd.service
            86ms gdm-plymouth.service
            82ms upower.service
            78ms systemd-tmpfiles-setup.service
            75ms wpa_supplicant.service
            41ms rtkit-daemon.service
            40ms geoclue.service
            38ms user@1000.service
            37ms systemd-update-utmp.service
            31ms plymouth-start.service
            14ms plymouth-read-write.service
             4ms sys-fs-fuse-connections.mount
```

**Comment by ryanvade** [comment]
After enabling Firewalld again: 
```
systemd-analyze blame
         20.448s firewalld.service
         20.250s plymouth-quit-wait.service
          6.507s systemd-journald.service
          4.580s dev-sda3.device
          3.774s systemd-modules-load.service
          3.265s colord.service
          3.139s plymouth-start.service
          3.098s alsa-restore.service
          2.993s NetworkManager.service
          2.992s thermald.service
          2.816s systemd-vconsole-setup.service
          1.586s gdm-plymouth.service
          1.479s avahi-daemon.service
          1.256s systemd-logind.service
          1.094s systemd-rfkill.service
          1.020s systemd-fsck@dev-disk-by\x2duuid-fca3eb5c\x2d2981\x2d44c6\x2d8108\x2d9eef32e823a7.service
           917ms systemd-journal-flush.service
           898ms systemd-sysctl.service
           729ms systemd-binfmt.service
           687ms systemd-tmpfiles-setup-dev.service
           555ms tmp.mount
           553ms dev-hugepages.mount
           526ms systemd-remount-fs.service
           526ms sys-kernel-debug.mount
           525ms dev-mqueue.mount
           497ms user@120.service
           466ms systemd-backlight@backlight:intel_backlight.service
           462ms accounts-daemon.service
           459ms systemd-udevd.service
           394ms systemd-udev-trigger.service
           341ms systemd-user-sessions.service
           316ms home.mount
           274ms systemd-timesyncd.service
           232ms freefall@-dev-sda.service
           210ms polkit.service
           210ms packagekit.service
           186ms proc-sys-fs-binfmt_misc.mount
           167ms bluetooth.service
           167ms systemd-random-seed.service
           150ms systemd-timedated.service
           149ms systemd-localed.service
           136ms sys-kernel-config.mount
           119ms wpa_supplicant.service
           117ms systemd-tmpfiles-setup.service
            97ms udisks2.service
            92ms upower.service
            67ms kmod-static-nodes.service
            63ms systemd-hostnamed.service
            41ms systemd-update-utmp.service
            40ms rtkit-daemon.service
            37ms user@1000.service
            30ms geoclue.service
            13ms plymouth-read-write.service
             5ms sys-fs-fuse-connections.mount
```

**Comment by t-woerner** [comment]
Do you have error messages in the logs for the boot?

**Comment by t-woerner** [comment]
Please enable debugging in firewalld by setting FIREWALLD_ARGS="--debug" in /etc/sysconfig/firewalld and add /var/log/firewalld to this issue. BTW: I am not sure if this file exists and if is used in Manjaro.
Which Manjaro version are you using?

**Comment by ryanvade** [comment]
/etc/sysconfig does not exist. 

Technically Manjaro is a rolling distribution, but I am using 15.09 version of Manjaro Core.

**Comment by t-woerner** [comment]
@ryanvade Please add these lines to firewalld.service for testing:
After=syslog.target
After=polkit.service
After=abrtd.service
The last one might not be needed as it does not seem to be available on your system

**Comment by t-woerner** [comment]
@EinerPetersen 
Please have a look at the development version of firewalld in the GIT repo. Some time before you asked about this, I have added support to use the restore commands of ip*tables and ebtables to be able to speed up the load, reload etc. It is done a bit different than your proposal to be able to provide feedback about failed things per item like services, etc. . Please have a look at http://www.firewalld.org/2016/01/firewalld-speed-up/

The speed up is not there if you are adding 10000 single rules with the direct interface, but you can see it if you are for example creating a service with 10000 ports. Enabling or disabling should be done in a second (depending on the machine).

I am about to add rule sets to the direct interface to provide a solution for bigger rule chunks that are applied in one operation. But the operation would fail as a whole if there is only one typo in one of the rules.

BTW: You are comparing two different things. The firewall rule set used with the iptables service is static and could either be applied completely or not at all. You are not able to simply enable a port without knowledge how and where to add to have the desired impact. Also there is no interface for simple integration in other services or applications...

**Comment by EinerPetersen** [comment]
Hi Thomas,

I agree, loading the individual rules (the one-at-a time),
iptables-restore would not exactly be ideal :-) ....

But, what could be done is something like this:
1) when you change/add an individual rule AND save it to the permanent
ruleset (the xml file) then you could do and iptables-save > {some_file}
(/etc/sysconfig/iptables is the default on mine) .... but it would
probably be a good idea to store it in the same place as the xml files
firewalld uses :-)
2) when you do a reload of all the rules (firewall-cmd --reload or a
restart of firewalld), just use the iptables-restore instead of the xml
files

My thinking :-)
1) The rules already exist in the order and place you want them because
they were inserted/created with firewalld
2) when you do an iptables-save of #1, all the rules are preserved in
the desired order and are known to be of correct syntax (or it would not
be in the tables that were saved :-)
3) when the entire ruleset is reloaded via iptables-restore, you already
know it's correct (as long as no intermediate change was made with
another tool :-)) it will load faster than doing it line-by-line from
the xml files the way firewall-cmd --reload or a restart of firewalld
currently do it.
4) Once everything has loaded, then in the background, reconcile any
change to the xml with the runtime
    - all good, just keep on going
    - difference, notify and possibly have an auto resolve based on
admin's spec
        - xml takes precedence .... fix and do an iptables-save
        - iptables restored takes precedence ..... adjust the xml from
iptables runtime and do and iptable-save
        - resolve manually ......


What I am doing now to minimize the downtime on reboot at the moment:
1) After any modification of the rules or before shutdown --
iptables-save => /etc/sysconfig/iptables
2) iptables is set to start at system reboot
3) IF I am going to change the firewall settings I manually stop
iptables, do an iptables-restore and then start firewalld
    - not great because when firewalld is started, no new connections to
the box work until firewalld finishes reloading all the rules --- in my
case it takes about 45 minutes.....
    - and to your point in the "BTW:" .... I can't take advantage of
firewalld's integration with other services/apps ... (I sure would like
to continue to use the new GUI tool to do the configuration of the rules
:-)) and I already am starting to have a need for this in other apps and
systems

The only real complaint I currently have with firewalld is that the
reload of all the rules (firewall-cmd --reload or restart of firewalld
or a reboot of the system for maintenance) takes to long.  The rest
seams to work the way I would expect so far :-)


Einer

**Comment by t-woerner** [comment]
Hi Einer,

45 Minutes is way too long. Why do you have so many rules? Are you using black or white listing? It would be good to have more information for optimization. 

Have you had a chance to test the development version from GIT? Is it faster or the same in your case?

To test the development version, you could do this:
(For Fedora < 23 or RHEL-7 you will need to replace python3-devel with python2-devel.)
```
sudo dnf install desktop-file-utils gettext intltool glib2 glib2-devel systemd-units docbook-style-xsl python3-devel
git clone https://github.com/t-woerner/firewalld.git
cd firewalld
./autogen.sh
make test-rpm
```

This will create rpm packages that you can install with dnf.

Thomas

**Comment by EinerPetersen** [comment]
Hi Thomas,

I am basically doing a combination or both black-listing and
white-listing..... and probably serious overkill/brute-force by some
standards :-) ..... I am accustomed to doing everything via iptables
directly so just getting used to firewalld (a little bit of a challenge
I'll admit :-))


I can send you what I have in both xml files and from iptables-restore
if you would like (nothing sensitive in either :-))

For my "Test/Proto-typing environment" I am running both Fedora 23 (on
workstation/laptop with 3.7Ghz quad core (8 exec threads) iNtel i7 and
32GB RAM at 1600Mhz) and CentOS EL7 (on 2x workstations/servers with 2 x
4.02 Ghz iNtel 2 cores (4 exec threads) and 8GB 2 channel RAM each....
getting the same performance on load out of either .... so not a
CPU/Memory speed/pressure problem ... no swap utilization and lots of
free RAM :-)
In my production environment I have 300+ bare-metal servers (all CentOS
EL7) and the minimum config is 4 x 4 core ( 8 exec threads each) @ 4Ghz,
256GB 3 channel RAM @ 1600Mhz .... still takes about 45 minutes on a
firewalld reload/restart .......

Do notice a lot of lock contention and system space CPU utilization
during reload or restart of firewalld (usually 2 threads running at
between 50% and 60% concurrently....thinking it's the xtables(?) lock
getting pounded when the ruleset is being inserted into iptables)

On the python devel ..... did you mean the other way around (... if <
(F23 or EL7) would need to install python3-devel instead of
python2-devel?... :-))

What I have installed on the workstations/servers (EL7) is
firewalld-0.3.9-14.el7.noarch and on the workstation/laptop (F23) is
firewalld-0.3.14.2-4.fc23.noarch .....

and THANKS! for the instructions for building the RPM from the GIT
...... I always have headaches when I build the RPMs :-)

I'll give the GIT build a try and see what happens :-)




Einer

**Comment by t-woerner** [comment]
Yes, please send me what you have in the xml files and in the iptables-save file. This would help for optimization.
BTW: For IP and also network black/white listing it might be good to use ipsets, as this is increasing the throughput of your firewall by reducing the rule count.

**Comment by EinerPetersen** [comment]
Hi Thomas,

Ok, the attached tgz is from /etc/firewalld (you'll want to extract it
into some temporary directory because it will extract as ./firewalld)
and a copy of the iptables-save is in
./firewalld/zones/iptables-2016-01-10...

Note: Yup ..... it's probably going to look really UGLY because I have
been using the "Firewall Config" GUI tool to build this stuff lately
..... I used to do all the rules by hand and it was a LOT cleaner/sane
:-) ..... Trying to accomplish the following:
1) Learn the tool
2) Make it easier to maintain the firewall rules
3) Keep rule loading as fast as possible on restarts

The way/logic I used to do the rules by hand:
Interface -> is the top zone
NIC (ARIN, APNIC, LACNIC, RIPE) -> addresses in zones
Country of origin -> addresses in NIC zones OR sub_NIC (like KRNIC ..)

Logic:
Traffic from origin -> Interface -> NIC -> Country
Address of greatest scope (like 1.0.0.0/8) would come into interface
eth0 and filter to APNIC (chain), IF no more addresses (so 1.0.0.1/32 is
where the traffic originated) then it would either: 1) use the default
action for the chain/zone (LOG and ACCEPT) OR 2) do something a bit more
detailed (LOG and DROP SSH) for example
    IF I want to DROP all traffic for APNIC, then the default action for
that chain would be LOG and DROP
    IF I want to DROP traffic for a specific NODE (/32) AND there are no
less specific CHAINS defined, then I can act on traffic specifically for
that traffic
    IF there is a less specific address (like I want to process traffic
for 1.0.1.0/24) then there would be another CHAIN ....
        so the whole thing would now look like:
Internet zone (Interface) -> NIC in Internet zone -> Country/Subnet zone
in NIC -> Smaller Subnet in Country zone -> smaller Subnet (until we get
to smallest in zone ... I stop at /29)
each zone is a chain, basically anywhere you see a -> ... it's a new
chain ....

Example:  
 Interface: source = 1.0.0.0/8 -> APNIC-chain
         APNIC: source = 1.0.0.1/24 -> KR
            KR: source = 1.0.0.1/29 -> KR_1
                KR_1: source = 1.0.0.1/32 -> KR_DROP or KR_ACCEPT
            KR_DROP: -> LOG
            KR_DROP: -> DROP
            KR_ACCEPT: -> LOG
            KR_ACCEPT: -> ACCEPT
            KR_DEFAULT: -> LOG
            KR_DEFAULT: -> ACCEPT
        APNIC_DROP: -> LOG
        APNIC_DROP: -> DROP
        APNIC_ACCEPT: -> LOG
        APNIC_ACCEPT: -> ACCEPT
        APNIC_DEFAULT: -> LOG
        APNIC_DEFAULT: -> DROP


It's a bit to maintain but it gives me a lot of control and information
(... I know where it's coming from and what I am doing with it and it's
all in syslog :-))
1) For the entry into chain, have to sort to least specific ip address
for the ip space
2) then in the chain most specific to least specific


Einer

**Comment by t-woerner** [comment]
@EinerPetersen Email attachments are ignored by github, please attach by using the web interface instead.

**Comment by EinerPetersen** [comment]
Hi Thomas,

I would prefer to send the xml and iptables-save output directly to you
as opposed to putting them on GIT .... I don't mind having you
specifically seeing/using them but I am not comfortable with the whole
world being able to see them :-)


Einer

**Comment by t-woerner** [comment]
Ok, no problem. My email address is listed in the headers of the firewalld files.

**Comment by t-woerner** [comment]
@EinerPetersen I had a look at your configuration.
Altogether you have around 200 zones with several source bindings per zone. The use of source bindings in this way results in the slowness and the high number of rules.

One solution would be to use rich rules with source addresses for black and white listing. This would reduce the rule amount.
The best solution would be to use the new firewalld version in the git repo. It offers ipset support, which is optimal for black and white listing. Only one rule would be needed for an ipset in the firewall.
firewalld will also manage the ipsets and the command line tool and also the firewall-config is able to handle them.

**Comment by t-woerner** [comment]
I have been working on a transaction model for firewalld lately. It groups firewall transactions together and applies them in one call.

With this I am able to start firewalld with your configuration in some seconds now - depending on the machine. The biggest part of this is to load the zone files and to create the D-Bus interfaces for the zones now.

I plan to push the transaction model this week into the git repository.

**Comment by t-woerner** [comment]
The transaction model has been pushed upstream, please give it a try if possible. I plan to create a new release in some days.

**Comment by t-woerner** [comment]
The version 0.4.2 has been released. It provides a transaction model that is speeding up load times a lot.
