### ISSUE TITLE
firewalld-offline-cmd aborts if a service is already enabled

### ISSUE THREAD

**Issue by clumens** [t-woerner/firewalld#82]
If I run this command in anaconda:

08:14:06,197 INFO program: Running... /usr/bin/firewall-offline-cmd --enabled --service=ssh --port=22001:tcp --port=6400:udp --service=tftp --service=smtp

Then firewall-offline-cmd gives me the following:

08:14:06,874 INFO program: Adding service 'ssh' to default zone.
08:14:06,874 INFO program: ALREADY_ENABLED: ssh
08:14:06,875 DEBUG program: Return code: 2

And doesn't appear to have done anything about the --port or --service options given.  It'd be nicer if the already enabled service didn't cause the program to abort.  I believe this is how it behaved up until the latest version.

**Comment by dashea** [comment]
This is caused by commit 14fecd41eb6be610179ff6e1b2534dd6171628be. Encountering one of these errors aborts the rest of the command, so firewall-offline-cmd either needs to go back to just ignoring them (or printing a warning or something), or provide some means of automatically continuing if one of these errors is encountered.
