### ISSUE TITLE
ERROR: ipset not usable, disabling ipset usage in firewall.

### ISSUE THREAD

**Issue by gentooo** [t-woerner/firewalld#95]
My system gentoo
4.5.0-gentoo
firewalld - 0.4
systemd

Apr 13 00:24:19 debian /firewalld[3469]: ERROR: ipset not usable, disabling ipset usage in firewall.
Apr 13 00:24:19 debian /firewalld[3469]: ERROR: ebtables not usable, disabling ethernet bridge firewal
Apr 13 00:24:19 debian /firewalld[3469]: FATAL ERROR: No IPv4 and IPv6 firewall.

**Comment by hwoarang** [comment]
Hi,

I believe your problem is similar to this[1] (but if you could provide a more verbose output that would be nice. For example, run 'firewalld --nofork --nopid --debug 5' or more

[1] https://github.com/t-woerner/firewalld/issues/79

So basically, iirc gentoo installs ipset in /sbin but default configuration in firewalld expects them in /usr/sbin. So it's probably a mistake in the gentoo ebuild.

**Comment by t-woerner** [comment]
O.k. the binaries should be auto detected in the build process. This needs to be addressed.

**Comment by hwoarang** [comment]
@t-woerner I will submit a PR asap
